baseURL = 'https://kittisci.co.uk/'
languageCode = 'en-gb'
title = 'Kittisci'
theme = 'hugo-coder'

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[params]
  author = 'Kittisci'
  description = 'Space, science, and games'
  avatarURL = ''
  darkModeToggle = true
  colorScheme = 'dark'

[[params.social]]
  name = 'GitHub'
  url = 'https://github.com/Kittisci-git'